version:  "3.8"
services:
  auth_db:
    image: postgres:13
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_database
    volumes:
      - auth_db_data:/var/lib/postgresql/data
